### ISSUE TITLE
Service fails to restart sometimes (port 7080 in use)

### ISSUE THREAD

**Issue by gabrielcossette** [litespeedtech/openlitespeed#163]
Hi,

I noticed that **lsws** service restart sometime fails (e.g. after a software update) because admin port 7080 is still in use:
```
[ERROR] HttpListener::start(): Can't listen at address adminListener: Address already in use!
[ERROR] HttpServer::addListener(adminListener) failed to create new listener
[ERROR] [config:admin:listener:adminListener] failed to start listener on address *:7080!
[ERROR] [config:admin:listener] No listener is available for admin virtual host!
[ERROR] Fatal error in configuration, exit! 
[NOTICE] [Child: 282657] Start shutting down gracefully ...
```
Is the delay between stop and start too short maybe?

I'm on CentOS 7 and I was able to reproduce the problem by running this command multiple times:

`systemctl restart lshttpd; sleep 5; journalctl | grep litespeed
`

And sometimes this will appear:
```
lswsctrl[282758]: [OK] litespeed: graceful stop.
lswsctrl[282770]: [OK] litespeed: pid=282783.
lswsctrl[282795]: [ERROR] litespeed is not running.
```
Thanks!

**Comment by litespeedtech** [comment]
The webAdmin may use continue to query and cause that issue. 
You may try call to stop the service multiple times to ensure the service is not running. 
We will fix this bug in the later release.

**Comment by gabrielcossette** [comment]
I believe it has been fixed, thanks!

**Comment by franciscopaniskaseker** [comment]
Today I receive:

```bash
2020-09-16 18:05:09.738870 [ERROR] HttpListener::start(): Can't listen at address adminListener: Address already in use!
2020-09-16 18:05:09.739731 [ERROR] HttpServer::addListener(adminListener) failed to create new listener
2020-09-16 18:05:09.739742 [ERROR] [config:admin:listener:adminListener] failed to start listener on address *:7080!
2020-09-16 18:05:09.739749 [ERROR] [config:admin:listener] No listener is available for admin virtual host!
2020-09-16 18:05:09.739776 [ERROR] Fatal error in configuration, exit!
```

During normal openlitespeed graceful restarts it get those errors.

I think the bug still exist.

**Comment by franciscopaniskaseker** [comment]
Maybe the 1.6.14 fix is related with this bug:

> [Bug Fix] Server should now correctly use a newly assigned unix domain socket address when the default socket address is already occupied.
