### ISSUE TITLE
Log is not piped to script

### ISSUE THREAD

**Issue by Niquit** [litespeedtech/openlitespeed#211]
Hi,

I have a problem with piped Logger configuration. I am using OLS 1.7.3.
Below is my config for that:

```
extprocessor Logger {
  type logger
  maxConns 1
  address 127.0.0.1:12345
  path $SERVER_ROOT/logger.pl
  instances 1
}

accessLog {
        pipedLogger Logger
        logReferer 1
        logUserAgent 1
}
```

The process for logger.pl script exist under main openlitespeed process. When I am testing this script it didn't get anything on stdin or in arguments.
The script is simple at the moment, just piping stdin to file like here:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:piped-logger

The script is working, because I put extra string inside script and it is write to output file.

So the main problem is, that log is not piped to script.

The second problem is that instances is not working. I defined 1, but every request is generating new child process of logger.pl.

I was looking of course in Google for any help but without success.

**Comment by litespeedtech** [comment]
I tested your conf locally, I did not see the log file created either.
I will debug this and will update you later.
You may also check if there is any issue such as permission or directory not exists.
Thanks
David

**Comment by litespeedtech** [comment]
I did some code change it locally, can you update to 1.7.7 to see if it works?
/usr/local/lsws/admin/misc/lsup.sh -e 1.7.7
Thanks
David

**Comment by Niquit** [comment]
Hi David,

I tested and there is errors:
`2020-11-19 12:09:17.254038 [NOTICE] [LocalWorker::workerExec] Config[Logger]: suExec uid 1004 gid 99 cmd /usr/loca/lsws/bin/log.pl, final uid 1004 gid 99.
2020-11-19 12:09:17.254052 [DEBUG] Check bwrap, pVHost: (nil)
2020-11-19 12:09:17.254061 [DEBUG] pVHost enableBwrap: 0, procConfig.getBwrap: 0
2020-11-19 12:09:17.254071 [ERROR] [LocalWorker::workerExec] Config[Logger]: cgidSuEXEC failed.`

uid 1004 - lsadm
gid 99 - nobody

Maybe it is not working with ArchLinux?

**Comment by litespeedtech** [comment]
Is this in 1.7.7? How about old version?
I never test on ArchLinux.
Thanks
David

**Comment by litespeedtech** [comment]
What is your log.pl file? Can you post here so that I can take a look?

**Comment by litespeedtech** [comment]
> Hi David,
> 
> I tested and there is errors:
> `2020-11-19 12:09:17.254038 [NOTICE] [LocalWorker::workerExec] Config[Logger]: suExec uid 1004 gid 99 cmd /usr/local/lsws/bin/log.pl, final uid 1004 gid 99. 2020-11-19 12:09:17.254052 [DEBUG] Check bwrap, pVHost: (nil) 2020-11-19 12:09:17.254061 [DEBUG] pVHost enableBwrap: 0, procConfig.getBwrap: 0 2020-11-19 12:09:17.254071 [ERROR] [LocalWorker::workerExec] Config[Logger]: cgidSuEXEC failed.`
> 
> uid 1004 - lsadm
> gid 99 - nobody
> 
> Maybe it is not working with ArchLinux?

The pid gid are good for that app to run. But need to check why it failed.
What is your config?
Also can you test 1.7.6? (lsup.sh -e 1.7.6)

**Comment by litespeedtech** [comment]
I just updated the code and fixed some other errors, and I tested with your scrip locally, and I can see the logs was piped to the file.
Please update to 1.7.7 again and test on your server.
/usr/local/lsws/admin/misc/lsup.sh -e 1.7.7
Thanks
David

**Comment by Niquit** [comment]
Hi David,

Thank you for your time, but this is still not working:
`2020-11-20 12:47:50.496379 [ERROR] [LocalWorker::workerExec] Config[Logger]: cgidSuEXEC failed.`

Did you tested it on ArchLinux?

**Comment by litespeedtech** [comment]
No. I did not test. I will spend time to check the reason why you get the "config[Logger]: cgidSuEXEC failed. " error.

**Comment by litespeedtech** [comment]
My test server is  ubuntu-14.04-x86_64, and the result is good.

I only add 
```
extprocessor Logger {
  type logger
  maxConns 1
  address 127.0.0.1:8088
  path $SERVER_ROOT/logger.pl
  instances 1
}

accessLog {
useServer               0
        pipedLogger Logger
        logReferer 1
        logUserAgent 1
}
``` 
to conf/vhosts/Example/vhconf.conf

root@david-ubuntu-14:/usr/local/lsws/bin# cat ../logger.pl 
#!/usr/bin/perl
open LOG, '>> /usr/local/lsws/logs/pipedaccess.log';
select LOG;
$| = 1;
while (<>)
{
   print LOG $_;
}

The permission is 
-rwxrwxrwx  1 root   root      122 Nov 19 13:58 logger.pl

**Comment by litespeedtech** [comment]
Can you check you permission?
Also can you try the updated 1.7.7, I added one log to track the error as you just mentioned.

**Comment by demyxco** [comment]
Any news on this? Log piping isn't working for me on 1.7.7 as well but I would rather stick to the stable releases.

**Comment by litespeedtech** [comment]
Can you please strace lscgid process

`strace -tt -T -f -s2000 -v -p <pid_of_lscgid_process>` 
post your output when try to start the pipe logger.

**Comment by demyxco** [comment]
It works now once I redid the steps but it appears to only work with this perl script; is the perl script the only viable option? I've even tried pointing the logger to a bash and php script, still won't output. Doing a `echo test | logger.sh` in terminal outputs `test` to the log file.

**Comment by litespeedtech** [comment]
It is likely a problem with the pipe logger script itself.
